# Service descriptor for OpenIG
apiVersion: v1
kind: Service
metadata:
  name: openig
spec:
  type: NodePort
  ports:
    - port: 80
      name:  port80
      targetPort: 8080
  selector:
    name: openig

---
# Service descriptor for the IG sample app described in the IG gateway guide
apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  type: NodePort
  ports:
    - port: 80
      name:  port80
      targetPort: 8081
  selector:
    name: sample-app